import React, { useState, useMemo } from 'react';
import { Recipe, FeedbackType, NutritionData } from '../types';
import { jsPDF } from 'jspdf';
import { 
  Clock, 
  Flame, 
  ChefHat,
  ArrowLeft, 
  Printer, 
  Share2, 
  CheckCircle, 
  AlertCircle, 
  ShoppingCart, 
  Mic, 
  ThumbsUp, 
  ThumbsDown, 
  MinusCircle,
  Dumbbell,
  CircleDot,
  Plus,
  Minus,
  FileText
} from 'lucide-react';

interface RecipeDetailProps {
  recipe: Recipe;
  onBack: () => void;
  onStartKitchen: () => void;
  onFeedback: (recipeTitle: string, type: FeedbackType) => void;
}

export const RecipeDetail: React.FC<RecipeDetailProps> = ({ recipe, onBack, onStartKitchen, onFeedback }) => {
  const [feedbackGiven, setFeedbackGiven] = useState<FeedbackType | null>(null);
  
  // Use a consistent default if servings_count is missing or 0
  const initialServings = (recipe.servings_count && recipe.servings_count > 0) ? recipe.servings_count : 4;
  const [servings, setServings] = useState(initialServings);
  const [viewMode, setViewMode] = useState<'PER_SERVING' | 'TOTAL'>('PER_SERVING');

  const handlePrint = () => {
    window.focus();
    window.print();
  };

  const buildRecipePdf = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 15;

    doc.setFillColor(59, 130, 246);
    doc.roundedRect(margin, y, 14, 14, 4, 4, 'F');
    
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.7);
    const hx = margin + 4;
    const hy = y + 11;
    doc.line(hx, hy, hx + 6, hy);
    doc.line(hx, hy, hx - 0.5, hy - 3);
    doc.line(hx + 6, hy, hx + 6.5, hy - 3);
    doc.line(hx - 0.5, hy - 3, hx + 6.5, hy - 3);
    doc.circle(hx + 0.8, hy - 4.5, 1.8, 'S');
    doc.circle(hx + 3, hy - 5.5, 2, 'S');
    doc.circle(hx + 5.2, hy - 4.5, 1.8, 'S');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text("PURE", margin + 19, y + 10.5);
    
    doc.setTextColor(59, 130, 246);
    doc.text("Chef", margin + 44, y + 10.5);
    
    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 18, 190, y + 18);
    y += 28;

    if (recipe.imageUrl) {
      try {
        const imgWidth = 170;
        const imgHeight = 110; 
        const format = recipe.imageUrl.includes('png') ? 'PNG' : 'JPEG';
        doc.addImage(recipe.imageUrl, format, margin, y, imgWidth, imgHeight);
        y += imgHeight + 15;
      } catch (e) {
        console.error("Could not add image to PDF", e);
      }
    }

    doc.setFontSize(24);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text(recipe.title, margin, y);
    y += 12;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    const descLines = doc.splitTextToSize(recipe.description, 170);
    doc.text(descLines, margin, y);
    y += (descLines.length * 5) + 10;

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Prep Time: ${recipe.prepTime} | Calories: ${recipe.calories} kcal`, margin, y);
    y += 15;

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("Ingredients", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    recipe.ingredients.forEach(ing => {
      const text = `${ing.isMissing ? '[ ]' : '[x]'} ${ing.amount} ${ing.name}`;
      doc.text(text, margin + 5, y);
      y += 7;
    });
    y += 10;

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("Instructions", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    recipe.instructions.forEach((step, i) => {
      const stepText = `${i + 1}. ${step}`;
      const splitStep = doc.splitTextToSize(stepText, 170);
      
      if (y + (splitStep.length * 5) > 280) {
        doc.addPage();
        y = 20;
      }
      
      doc.text(splitStep, margin, y);
      y += (splitStep.length * 5) + 6;
    });

    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by PURE Chef AI - Your Personal AI Kitchen Assistant", margin, 285);

    return doc;
  };

  const handleSaveAsPDF = () => {
    const doc = buildRecipePdf();
    doc.save(`${recipe.title.replace(/\s+/g, '_')}_Recipe.pdf`);
  };

  const handleShare = async () => {
    const fileName = `${recipe.title.replace(/\s+/g, '_')}_Recipe.pdf`;
    const doc = buildRecipePdf();
    const pdfBlob = doc.output("blob");
    const pdfFile = new File([pdfBlob], fileName, { type: "application/pdf" });

    const canShareFiles =
      typeof navigator !== "undefined" &&
      typeof navigator.share === "function" &&
      typeof navigator.canShare === "function" &&
      navigator.canShare({ files: [pdfFile] });

    if (canShareFiles) {
      try {
        await navigator.share({
          title: `Recipe: ${recipe.title}`,
          text: `Sharing ${recipe.title} as PDF`,
          files: [pdfFile],
        });
        return;
      } catch (err) {
        if ((err as Error).name === 'AbortError') return;
        console.error("PDF share failed, falling back to download", err);
      }
    }

    // Fallback for devices/browsers that do not support sharing files.
    doc.save(fileName);
    alert("PDF sharing is not supported on this device. The recipe PDF was downloaded; please share that file.");
  };

  const submitFeedback = (type: FeedbackType) => {
    setFeedbackGiven(type);
    onFeedback(recipe.title, type);
  };

  const currentNutrition = useMemo(() => {
    // Ensure we have a valid serving count for baseline calculations
    const originalServings = (recipe.servings_count && recipe.servings_count > 0) ? recipe.servings_count : initialServings;
    
    // Robust parsing for AI-generated numbers (handles strings and missing fields)
    const getVal = (obj: any, key: string) => {
      const val = obj ? obj[key] : undefined;
      if (val === undefined || val === null) return null;
      const parsed = parseFloat(String(val).replace(/[^0-9.]/g, ''));
      return isNaN(parsed) ? null : parsed;
    };

    const getBase = (key: string) => {
      const perServing = getVal(recipe.nutrition_per_serving, key);
      if (perServing !== null) return perServing;
      
      const total = getVal(recipe.nutrition_total, key);
      if (total !== null) return total / originalServings;
      
      // Fallback to top-level calories if specific nutrition objects are missing
      if (key === 'calories' && recipe.calories) {
        return parseFloat(String(recipe.calories)) / originalServings;
      }
      
      return 0;
    };

    const baseCalories = getBase('calories');
    const baseProtein = getBase('protein_g');
    const baseCarbs = getBase('carbs_g');
    const baseFat = getBase('fat_g');

    const multiplier = viewMode === 'PER_SERVING' ? 1 : servings;

    return {
      calories: Math.round(baseCalories * multiplier),
      protein_g: Math.round(baseProtein * multiplier),
      carbs_g: Math.round(baseCarbs * multiplier),
      fat_g: Math.round(baseFat * multiplier),
    };
  }, [recipe, servings, viewMode, initialServings]);

  const missingIngredients = recipe.ingredients.filter(ing => ing.isMissing);
  const isGapRecipe = missingIngredients.length === 1;

  return (
    <div className="max-w-4xl mx-auto bg-white rounded-3xl overflow-hidden shadow-xl animate-in fade-in slide-in-from-bottom-4 duration-500 mb-12">
      <div className="print-only-logo" aria-hidden="true">
        <div className="print-only-logo-mark">
          <ChefHat size={14} />
        </div>
        <div className="print-only-logo-wordmark">
          <span>PURE</span>
          <span className="print-only-logo-chef">Chef</span>
        </div>
      </div>

      <div className="relative h-72 md:h-96">
        <img 
          src={recipe.imageUrl || `https://picsum.photos/seed/${recipe.id}/1200/800`} 
          alt={recipe.title}
          className="w-full h-full object-cover"
        />
        <button 
          type="button"
          onClick={onBack}
          className="absolute top-6 left-6 p-2 bg-white/90 backdrop-blur rounded-full shadow-lg hover:scale-110 transition-transform no-print"
        >
          <ArrowLeft size={24} className="text-blue-600" />
        </button>
        {isGapRecipe && (
          <div className="absolute top-6 right-6 px-4 py-2 bg-amber-400 text-amber-900 font-bold rounded-full shadow-lg flex items-center gap-2 animate-bounce no-print">
            <ShoppingCart size={18} />
            Just 1 item away!
          </div>
        )}
      </div>

      <div className="p-8 md:p-12">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-4xl font-bold text-slate-900 mb-2">{recipe.title}</h1>
            <p className="text-slate-600 text-lg max-w-2xl">{recipe.description}</p>
          </div>
          <div className="flex flex-wrap gap-2 no-print">
            <button 
              type="button"
              onClick={onStartKitchen}
              className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white font-bold rounded-2xl hover:bg-blue-700 transition-all shadow-lg shadow-blue-100"
            >
              <Mic size={20} />
              Kitchen Mode
            </button>
            <button 
              type="button"
              onClick={handleSaveAsPDF}
              title="Save as PDF"
              className="p-3 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 transition-colors flex items-center gap-2"
            >
              <FileText size={20} />
              <span className="hidden sm:inline font-bold text-sm">Save PDF</span>
            </button>
            <button 
              type="button"
              onClick={handleShare} 
              title="Share Recipe"
              className="p-3 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 transition-colors"
            >
              <Share2 size={20} />
            </button>
            <button 
              type="button"
              onClick={handlePrint} 
              title="Print Recipe"
              className="p-3 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 transition-colors"
            >
              <Printer size={20} />
            </button>
          </div>
        </div>

        <div className="mb-12 bg-slate-50 border border-slate-100 rounded-[2rem] p-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
            <div>
              <h3 className="text-xl font-bold text-slate-900">Nutrition Breakdown</h3>
              <p className="text-sm text-slate-500 mt-1">
                {recipe.is_estimated ? 'Nutrition is estimated and may vary.' : `Verified via ${recipe.nutrition_source || 'Gemini AI'}`}
              </p>
            </div>
            
            <div className="flex flex-wrap items-center gap-4 no-print">
              <div className="flex items-center bg-white border border-slate-200 rounded-xl p-1">
                <button 
                  type="button"
                  onClick={() => setServings(s => Math.max(1, s - 1))}
                  className="p-2 text-slate-500 hover:text-blue-600 transition-colors"
                >
                  <Minus size={16} />
                </button>
                <div className="px-4 text-center">
                  <span className="block text-[10px] font-bold text-slate-400 uppercase leading-none">Servings</span>
                  <span className="text-sm font-bold text-slate-800">{servings}</span>
                </div>
                <button 
                  type="button"
                  onClick={() => setServings(s => Math.min(12, s + 1))}
                  className="p-2 text-slate-500 hover:text-blue-600 transition-colors"
                >
                  <Plus size={16} />
                </button>
              </div>

              <div className="flex bg-white border border-slate-200 rounded-xl p-1">
                <button 
                  type="button"
                  onClick={() => setViewMode('PER_SERVING')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${viewMode === 'PER_SERVING' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-500 hover:text-slate-800'}`}
                >
                  Per Serving
                </button>
                <button 
                  type="button"
                  onClick={() => setViewMode('TOTAL')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${viewMode === 'TOTAL' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-500 hover:text-slate-800'}`}
                >
                  Total Recipe
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
              <div className="w-10 h-10 bg-orange-50 text-orange-600 rounded-xl flex items-center justify-center mb-3">
                <Flame size={20} />
              </div>
              <span className="text-2xl font-bold text-slate-800">{currentNutrition.calories}</span>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">kcal</span>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
              <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center mb-3">
                <Dumbbell size={20} />
              </div>
              <span className="text-2xl font-bold text-slate-800">{currentNutrition.protein_g}g</span>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Protein</span>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
              <div className="w-10 h-10 bg-amber-50 text-amber-600 rounded-xl flex items-center justify-center mb-3">
                <CircleDot size={20} />
              </div>
              <span className="text-2xl font-bold text-slate-800">{currentNutrition.carbs_g}g</span>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Carbs</span>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
              <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center mb-3">
                <CircleDot size={20} />
              </div>
              <span className="text-2xl font-bold text-slate-800">{currentNutrition.fat_g}g</span>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Fat</span>
            </div>
          </div>
        </div>

        {isGapRecipe && (
          <div className="mb-8 p-6 bg-amber-50 border-2 border-dashed border-amber-200 rounded-3xl flex flex-col md:flex-row items-center justify-between gap-6 no-print">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-amber-100 rounded-2xl flex items-center justify-center text-amber-600">
                <AlertCircle size={28} />
              </div>
              <div>
                <p className="font-bold text-amber-900 text-lg">One missing piece...</p>
                <p className="text-amber-700">If you buy <span className="font-bold underline">{missingIngredients[0].name}</span>, you can unlock this meal!</p>
              </div>
            </div>
            <a 
              href={`https://www.instacart.com/store/s?k=${encodeURIComponent(missingIngredients[0].name)}`} 
              target="_blank" 
              rel="noopener noreferrer"
              className="w-full md:w-auto flex items-center justify-center gap-3 bg-amber-400 hover:bg-amber-500 text-amber-900 font-bold py-4 px-8 rounded-2xl shadow-lg shadow-amber-200 transition-all hover:scale-[1.02]"
            >
              <ShoppingCart size={20} />
              Order on Instacart
            </a>
          </div>
        )}

        <div className="flex flex-wrap gap-6 mb-12 py-6 border-y border-blue-50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg text-blue-600">
              <Clock size={24} />
            </div>
            <div>
              <p className="text-sm text-slate-500 font-medium">Prep Time</p>
              <p className="text-lg font-bold text-slate-800">{recipe.prepTime}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-12">
          <div className="lg:col-span-1">
            <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              Ingredients
            </h3>
            <ul className="space-y-4">
              {recipe.ingredients.map((ing, i) => (
                <li key={i} className={`flex items-start gap-3 p-3 rounded-xl transition-all ${ing.isMissing ? 'bg-amber-50 text-amber-900 border border-amber-200' : 'bg-blue-50/50 text-blue-800'}`}>
                  <div className="mt-1">
                    {ing.isMissing ? <AlertCircle size={18} className="text-amber-500" /> : <CheckCircle size={18} />}
                  </div>
                  <div>
                    <span className="font-bold">{ing.amount}</span> {ing.name}
                    {ing.isMissing && <p className="text-xs font-semibold mt-1 uppercase tracking-tighter no-print">Quick Trip Needed</p>}
                  </div>
                </li>
              ))}
            </ul>
          </div>

          <div className="lg:col-span-2">
            <h3 className="text-xl font-bold text-slate-900 mb-6">Instructions</h3>
            <div className="space-y-8">
              {recipe.instructions.map((step, i) => (
                <div key={i} className="flex gap-6">
                  <span className="flex-shrink-0 w-10 h-10 bg-blue-100 text-blue-700 font-bold rounded-full flex items-center justify-center">
                    {i + 1}
                  </span>
                  <p className="text-slate-700 leading-relaxed pt-2">
                    {step}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-12 pt-12 border-t border-slate-100 no-print">
          <div className="bg-slate-50 p-8 rounded-[2rem] text-center">
            <h3 className="text-xl font-bold text-slate-900 mb-2">How was this meal?</h3>
            <p className="text-slate-500 mb-8">Your feedback helps PURE Chef learn your unique palate.</p>
            
            {feedbackGiven ? (
              <div className="flex flex-col items-center gap-3 animate-in fade-in zoom-in duration-300">
                <div className="w-16 h-16 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center">
                  <CheckCircle size={32} />
                </div>
                <p className="font-bold text-blue-800">Taste memory updated!</p>
                <p className="text-sm text-slate-400">Next time, your recipes will be even better.</p>
              </div>
            ) : (
              <div className="flex flex-wrap justify-center gap-4">
                <button 
                  type="button"
                  onClick={() => submitFeedback('LOVED')}
                  className="flex items-center gap-2 px-6 py-4 bg-white border-2 border-slate-100 hover:border-blue-500 hover:bg-blue-50 text-slate-700 hover:text-blue-700 font-bold rounded-2xl transition-all hover:scale-105"
                >
                  <ThumbsUp size={20} className="text-blue-500" />
                  Loved it
                </button>
                <button 
                  type="button"
                  onClick={() => submitFeedback('OKAY')}
                  className="flex items-center gap-2 px-6 py-4 bg-white border-2 border-slate-100 hover:border-amber-500 hover:bg-amber-50 text-slate-700 hover:text-amber-700 font-bold rounded-2xl transition-all hover:scale-105"
                >
                  <MinusCircle size={20} className="text-amber-500" />
                  It was okay
                </button>
                <button 
                  type="button"
                  onClick={() => submitFeedback('DISLIKED')}
                  className="flex items-center gap-2 px-6 py-4 bg-white border-2 border-slate-100 hover:border-red-500 hover:bg-red-50 text-slate-700 hover:text-red-700 font-bold rounded-2xl transition-all hover:scale-105"
                >
                  <ThumbsDown size={20} className="text-red-500" />
                  Not for me
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};